package com.app.upadrapp.utils

object Constant {
    const val WELCOME_SCREEN = "WELCOME_SCREEN"
    const val LOGIN_SCREEN = "LOGIN_SCREEN"
    const val SIGNUP_SCREEN = "SIGNUP_SCREEN"
    const val FORGOT_PASSWORD_SCREEN = "FORGOT_PASSWORD_SCREEN"
    const val VERIFY_OTP_SCREEN = "VERIFY_OTP_SCREEN"
    const val CHANGE_PASSWORD_SCREEN = "CHANGE_PASSWORD_SCREEN"
    const val HOME_SCREEN = "HOME_SCREEN"
    const val PREP_PROCESS_OVERVIEW_SCREEN ="PREP_PROCESS_OVERVIEW_SCREEN"
}